name: C:\Users\story645\Anaconda\envs\py35
dependencies:
- _license=1.1=py35_1
- alabaster=0.7.6=py35_0
- anaconda=2.4.1=np110py35_0
- anaconda-client=1.2.1=py35_0
- argcomplete=1.0.0=py35_1
- astropy=1.0.6=np110py35_0
- babel=2.1.1=py35_0
- beautifulsoup4=4.4.1=py35_0
- bitarray=0.8.1=py35_1
- blaze-core=0.8.3=py35_0
- bokeh=0.10.0=py35_0
- boto=2.38.0=py35_0
- bottleneck=1.0.0=np110py35_0
- bzip2=1.0.6=vc14_2
- cffi=1.2.1=py35_0
- clyent=1.2.0=py35_0
- colorama=0.3.3=py35_0
- comtypes=1.1.2=py35_0
- configobj=5.0.6=py35_0
- console_shortcut=0.1.1=py35_1
- cryptography=1.0.2=py35_0
- curl=7.45.0=vc14_0
- cycler=0.9.0=py35_0
- cython=0.23.4=py35_0
- cytoolz=0.7.4=py35_0
- datashape=0.4.7=np110py35_1
- decorator=4.0.4=py35_0
- docutils=0.12=py35_1
- dynd-python=0.7.0=py35_0
- fastcache=1.0.2=py35_0
- flask=0.10.1=py35_1
- freetype=2.5.5=vc14_0
- greenlet=0.4.9=py35_0
- h5py=2.5.0=np110py35_4
- hdf5=1.8.15.1=vc14_4
- idna=2.0=py35_0
- ipykernel=4.1.1=py35_0
- ipython=4.0.1=py35_0
- ipython-notebook=4.0.4=py35_3
- ipython-qtconsole=4.0.1=py35_4
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.0=py35_0
- itsdangerous=0.24=py35_0
- jdcal=1.0=py35_0
- jedi=0.9.0=py35_0
- jinja2=2.8=py35_0
- jpeg=8d=vc14_0
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_1
- jupyter_client=4.1.1=py35_0
- jupyter_console=4.0.3=py35_0
- jupyter_core=4.0.6=py35_0
- launcher=1.0.0=4
- libdynd=0.7.0=0
- libpng=1.6.17=vc14_1
- libsodium=1.0.3=0
- libtiff=4.0.6=vc14_1
- llvmlite=0.8.0=py35_0
- lxml=3.4.4=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.0=np110py35_0
- menuinst=1.3.1=py35_0
- mistune=0.7.1=py35_0
- msvc_runtime=1.0.1=vc14_0
- multipledispatch=0.4.8=py35_0
- nbconvert=4.0.0=py35_0
- nbformat=4.0.1=py35_0
- networkx=1.10=py35_0
- nltk=3.1=py35_0
- node-webkit=0.10.1=0
- nose=1.3.7=py35_0
- notebook=4.0.6=py35_0
- numba=0.22.1=np110py35_0
- numexpr=2.4.4=np110py35_0
- numpy=1.10.1=py35_0
- odo=0.3.4=py35_0
- openpyxl=2.2.6=py35_0
- openssl=1.0.2d=vc14_0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- patsy=0.4.0=np110py35_0
- pep8=1.6.2=py35_0
- pickleshare=0.5=py35_0
- pillow=3.0.0=py35_1
- pip=7.1.2=py35_0
- ply=3.8=py35_0
- psutil=3.3.0=py35_0
- py=1.4.30=py35_0
- pyasn1=0.1.9=py35_0
- pycosat=0.6.1=py35_0
- pycparser=2.14=py35_0
- pycrypto=2.6.1=py35_3
- pycurl=7.19.5.1=py35_1
- pyflakes=1.0.0=py35_0
- pygments=2.0.2=py35_0
- pyopenssl=0.15.1=py35_1
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_4
- pyreadline=2.1=py35_0
- pytables=3.2.2=np110py35_1
- pytest=2.8.1=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pywin32=219=py35_1
- pyyaml=3.11=py35_2
- pyzmq=14.7.0=py35_1
- qt=4.8.7=vc14_5
- qtconsole=4.1.1=py35_0
- requests=2.8.1=py35_0
- rope=0.9.4=py35_1
- scikit-image=0.11.3=np110py35_0
- scikit-learn=0.17=np110py35_1
- scipy=0.16.0=np110py35_0
- setuptools=18.5=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_2
- six=1.10.0=py35_0
- snowballstemmer=1.2.0=py35_0
- sockjs-tornado=1.0.1=py35_0
- sphinx=1.3.1=py35_0
- sphinx_rtd_theme=0.1.7=py35_0
- spyder=2.3.8=py35_0
- spyder-app=2.3.8=py35_0
- sqlalchemy=1.0.9=py35_0
- statsmodels=0.6.1=np110py35_0
- sympy=0.7.6.1=py35_0
- tk=8.5.18=vc14_0
- toolz=0.7.4=py35_0
- tornado=4.3=py35_0
- traitlets=4.0.0=py35_0
- ujson=1.33=py35_0
- unicodecsv=0.14.1=py35_0
- werkzeug=0.11.2=py35_0
- wheel=0.26.0=py35_1
- xlrd=0.9.4=py35_0
- xlsxwriter=0.7.7=py35_0
- xlwings=0.5.0=py35_0
- xlwt=1.0.0=py35_0
- zeromq=4.1.3=vc14_1
- zlib=1.2.8=vc14_2
- pip:
  - blaze==0.8.3
  - dynd==5a2f274
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - rope-py3k-0.9.4==1
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.2

